export interface Country {
  name: string
  iso2: string // ISO 3166-1 alpha-2
  dialCode: string // without leading +
}

// Compute emoji flag from ISO 3166-1 alpha-2 code
export function flagEmoji(iso2: string): string {
  if (!iso2 || iso2.length !== 2) return ''
  const codePoints = [...iso2.toUpperCase()].map((c) => 127397 + c.charCodeAt(0))
  return String.fromCodePoint(...codePoints)
}

// Common + comprehensive list of countries and dialing codes (subset of ITU E.164)
// Note: Some countries/territories share +1 (NANP). We list them separately with dialCode "1".
export const countries: Country[] = [
  { name: 'United States', iso2: 'US', dialCode: '1' },
  { name: 'Canada', iso2: 'CA', dialCode: '1' },
  { name: 'United Kingdom', iso2: 'GB', dialCode: '44' },
  { name: 'Australia', iso2: 'AU', dialCode: '61' },
  { name: 'New Zealand', iso2: 'NZ', dialCode: '64' },
  { name: 'India', iso2: 'IN', dialCode: '91' },
  { name: 'United Arab Emirates', iso2: 'AE', dialCode: '971' },
  { name: 'Saudi Arabia', iso2: 'SA', dialCode: '966' },
  { name: 'Qatar', iso2: 'QA', dialCode: '974' },
  { name: 'Kuwait', iso2: 'KW', dialCode: '965' },
  { name: 'Bahrain', iso2: 'BH', dialCode: '973' },
  { name: 'Oman', iso2: 'OM', dialCode: '968' },
  { name: 'Turkey', iso2: 'TR', dialCode: '90' },
  { name: 'Israel', iso2: 'IL', dialCode: '972' },
  { name: 'Jordan', iso2: 'JO', dialCode: '962' },
  { name: 'Lebanon', iso2: 'LB', dialCode: '961' },
  { name: 'Egypt', iso2: 'EG', dialCode: '20' },
  { name: 'South Africa', iso2: 'ZA', dialCode: '27' },
  { name: 'Nigeria', iso2: 'NG', dialCode: '234' },
  { name: 'Kenya', iso2: 'KE', dialCode: '254' },
  { name: 'Tanzania', iso2: 'TZ', dialCode: '255' },
  { name: 'Uganda', iso2: 'UG', dialCode: '256' },
  { name: 'Ghana', iso2: 'GH', dialCode: '233' },
  { name: 'Morocco', iso2: 'MA', dialCode: '212' },
  { name: 'Algeria', iso2: 'DZ', dialCode: '213' },
  { name: 'Tunisia', iso2: 'TN', dialCode: '216' },
  { name: 'Libya', iso2: 'LY', dialCode: '218' },
  { name: 'Ethiopia', iso2: 'ET', dialCode: '251' },
  { name: 'Cameroon', iso2: 'CM', dialCode: '237' },
  { name: 'Senegal', iso2: 'SN', dialCode: '221' },
  { name: 'Côte d’Ivoire', iso2: 'CI', dialCode: '225' },
  { name: 'Rwanda', iso2: 'RW', dialCode: '250' },
  { name: 'Gambia', iso2: 'GM', dialCode: '220' },
  { name: 'Sierra Leone', iso2: 'SL', dialCode: '232' },
  { name: 'Guinea', iso2: 'GN', dialCode: '224' },

  { name: 'Germany', iso2: 'DE', dialCode: '49' },
  { name: 'France', iso2: 'FR', dialCode: '33' },
  { name: 'Spain', iso2: 'ES', dialCode: '34' },
  { name: 'Italy', iso2: 'IT', dialCode: '39' },
  { name: 'Netherlands', iso2: 'NL', dialCode: '31' },
  { name: 'Belgium', iso2: 'BE', dialCode: '32' },
  { name: 'Switzerland', iso2: 'CH', dialCode: '41' },
  { name: 'Austria', iso2: 'AT', dialCode: '43' },
  { name: 'Sweden', iso2: 'SE', dialCode: '46' },
  { name: 'Norway', iso2: 'NO', dialCode: '47' },
  { name: 'Denmark', iso2: 'DK', dialCode: '45' },
  { name: 'Finland', iso2: 'FI', dialCode: '358' },
  { name: 'Ireland', iso2: 'IE', dialCode: '353' },
  { name: 'Portugal', iso2: 'PT', dialCode: '351' },
  { name: 'Greece', iso2: 'GR', dialCode: '30' },
  { name: 'Poland', iso2: 'PL', dialCode: '48' },
  { name: 'Czechia', iso2: 'CZ', dialCode: '420' },
  { name: 'Slovakia', iso2: 'SK', dialCode: '421' },
  { name: 'Hungary', iso2: 'HU', dialCode: '36' },
  { name: 'Romania', iso2: 'RO', dialCode: '40' },
  { name: 'Bulgaria', iso2: 'BG', dialCode: '359' },
  { name: 'Croatia', iso2: 'HR', dialCode: '385' },
  { name: 'Slovenia', iso2: 'SI', dialCode: '386' },
  { name: 'Serbia', iso2: 'RS', dialCode: '381' },
  { name: 'Bosnia and Herzegovina', iso2: 'BA', dialCode: '387' },
  { name: 'North Macedonia', iso2: 'MK', dialCode: '389' },
  { name: 'Albania', iso2: 'AL', dialCode: '355' },
  { name: 'Montenegro', iso2: 'ME', dialCode: '382' },
  { name: 'Lithuania', iso2: 'LT', dialCode: '370' },
  { name: 'Latvia', iso2: 'LV', dialCode: '371' },
  { name: 'Estonia', iso2: 'EE', dialCode: '372' },
  { name: 'Ukraine', iso2: 'UA', dialCode: '380' },
  { name: 'Belarus', iso2: 'BY', dialCode: '375' },
  { name: 'Iceland', iso2: 'IS', dialCode: '354' },
  { name: 'Luxembourg', iso2: 'LU', dialCode: '352' },
  { name: 'Malta', iso2: 'MT', dialCode: '356' },
  { name: 'Cyprus', iso2: 'CY', dialCode: '357' },
  { name: 'Andorra', iso2: 'AD', dialCode: '376' },
  { name: 'San Marino', iso2: 'SM', dialCode: '378' },
  { name: 'Monaco', iso2: 'MC', dialCode: '377' },
  { name: 'Vatican City', iso2: 'VA', dialCode: '39' },

  { name: 'Mexico', iso2: 'MX', dialCode: '52' },
  { name: 'Brazil', iso2: 'BR', dialCode: '55' },
  { name: 'Argentina', iso2: 'AR', dialCode: '54' },
  { name: 'Chile', iso2: 'CL', dialCode: '56' },
  { name: 'Colombia', iso2: 'CO', dialCode: '57' },
  { name: 'Peru', iso2: 'PE', dialCode: '51' },
  { name: 'Uruguay', iso2: 'UY', dialCode: '598' },
  { name: 'Paraguay', iso2: 'PY', dialCode: '595' },
  { name: 'Bolivia', iso2: 'BO', dialCode: '591' },
  { name: 'Ecuador', iso2: 'EC', dialCode: '593' },
  { name: 'Venezuela', iso2: 'VE', dialCode: '58' },
  { name: 'Costa Rica', iso2: 'CR', dialCode: '506' },
  { name: 'Panama', iso2: 'PA', dialCode: '507' },
  { name: 'Guatemala', iso2: 'GT', dialCode: '502' },
  { name: 'El Salvador', iso2: 'SV', dialCode: '503' },
  { name: 'Honduras', iso2: 'HN', dialCode: '504' },
  { name: 'Nicaragua', iso2: 'NI', dialCode: '505' },
  { name: 'Dominican Republic', iso2: 'DO', dialCode: '1' },
  { name: 'Cuba', iso2: 'CU', dialCode: '53' },
  { name: 'Haiti', iso2: 'HT', dialCode: '509' },
  { name: 'Jamaica', iso2: 'JM', dialCode: '1' },
  { name: 'Trinidad and Tobago', iso2: 'TT', dialCode: '1' },
  { name: 'Barbados', iso2: 'BB', dialCode: '1' },
  { name: 'The Bahamas', iso2: 'BS', dialCode: '1' },
  { name: 'Belize', iso2: 'BZ', dialCode: '501' },
  { name: 'Guyana', iso2: 'GY', dialCode: '592' },
  { name: 'Suriname', iso2: 'SR', dialCode: '597' },

  { name: 'China', iso2: 'CN', dialCode: '86' },
  { name: 'Hong Kong', iso2: 'HK', dialCode: '852' },
  { name: 'Macau', iso2: 'MO', dialCode: '853' },
  { name: 'Taiwan', iso2: 'TW', dialCode: '886' },
  { name: 'Japan', iso2: 'JP', dialCode: '81' },
  { name: 'South Korea', iso2: 'KR', dialCode: '82' },
  { name: 'Vietnam', iso2: 'VN', dialCode: '84' },
  { name: 'Thailand', iso2: 'TH', dialCode: '66' },
  { name: 'Malaysia', iso2: 'MY', dialCode: '60' },
  { name: 'Singapore', iso2: 'SG', dialCode: '65' },
  { name: 'Indonesia', iso2: 'ID', dialCode: '62' },
  { name: 'Philippines', iso2: 'PH', dialCode: '63' },
  { name: 'Cambodia', iso2: 'KH', dialCode: '855' },
  { name: 'Laos', iso2: 'LA', dialCode: '856' },
  { name: 'Brunei', iso2: 'BN', dialCode: '673' },
  { name: 'Myanmar', iso2: 'MM', dialCode: '95' },
  { name: 'Sri Lanka', iso2: 'LK', dialCode: '94' },
  { name: 'Nepal', iso2: 'NP', dialCode: '977' },
  { name: 'Pakistan', iso2: 'PK', dialCode: '92' },
  { name: 'Bangladesh', iso2: 'BD', dialCode: '880' },
  { name: 'Afghanistan', iso2: 'AF', dialCode: '93' },
  { name: 'Iran', iso2: 'IR', dialCode: '98' },
  { name: 'Iraq', iso2: 'IQ', dialCode: '964' },
  { name: 'Syria', iso2: 'SY', dialCode: '963' },
  { name: 'Yemen', iso2: 'YE', dialCode: '967' },

  { name: 'Fiji', iso2: 'FJ', dialCode: '679' },
  { name: 'Papua New Guinea', iso2: 'PG', dialCode: '675' },
  { name: 'Samoa', iso2: 'WS', dialCode: '685' },
  { name: 'Tonga', iso2: 'TO', dialCode: '676' },
  { name: 'Vanuatu', iso2: 'VU', dialCode: '678' },
  { name: 'Kiribati', iso2: 'KI', dialCode: '686' },

  // Microstates and territories
  { name: 'Puerto Rico', iso2: 'PR', dialCode: '1' },
  { name: 'Guam', iso2: 'GU', dialCode: '1' },
  { name: 'U.S. Virgin Islands', iso2: 'VI', dialCode: '1' },
  { name: 'Bermuda', iso2: 'BM', dialCode: '1' },
  { name: 'Cayman Islands', iso2: 'KY', dialCode: '1' },
  { name: 'Isle of Man', iso2: 'IM', dialCode: '44' },
  { name: 'Jersey', iso2: 'JE', dialCode: '44' },
  { name: 'Guernsey', iso2: 'GG', dialCode: '44' },
]
